language: elixir
cache:
  directories:
    - deps
services:
  - docker
  - postgresql
addons:
  postgresql: "9.6"
  apt:
    packages:
      - docker-ce
elixir:
  - 1.5.2
otp_release:
  - 20.1.2
notifications:
  slack:
    rooms:
      - secure: "u7uYfmURAOxH5f+aZUYDlbKNUHz+7Ekd7U5WsZAYjWXbx+ILnLy3ox4wJsubWxO39zyuNMRYwwASV15b7S1u9hgP0m5kE5yxrzq7H7HkN16b07HUMHjOvNmNn98FC6eZBdMtJ5DW8HhPTr9oUshuYBGTOas+WN+vX5RARKOlW4l/4vlyXgDCKEWt2O+fx/svJ0W+Kq1fpn4DdxFGUkwbcsFOFjjEeslNY4rfb2WEFWoYLsPJgCBW+vfdEaLVu2vlFSSKSoykvbTqt/m5JxB8SLX+9Oel36PdC3JnG5qFAW8RN92EQXOKJ6MxAnyQkd68cUkkPGSVWfEGC6KnfC8kwUwEzz5VMEwA5gk6io0AwlmfSbN7HBSMuyaT5DlFHx6VBPe19tsjiFDCAE9cgOyGOAwujg66AbeZhzLwuo+VYpjH1uhplu40DpIm8kLE7w6r2ACJcz8Amm4T4mWAGTdqpDxcOPTSNwYStfE2h6+VT+nygdtvtEgmjcfxMZ7r1a2V+Hb197y5isTqEWV1YszrwHNCsW4Q1KxqnSOLsCvOgyo6qFdNrpYhEgGK5uc4k/yfo7Im6xxBI1whNQ/B0PdHau4MLudJfX6qHjrSQKqzZ16PWZ76Oa1AcYn1m05Ck6v6e30/6gmsI9YXA0kgn5x3PalK/TLvcBGLfgIo42dlFLg="
    on_success: always
env:
  global:
    # - Chart=event_manager
    - MIX_ENV=test
    - DOCKER_HUB_ACCOUNT=edenlabllc
    - TRUNK_BRANCH="master"
    # Docker and GitHub credentials
    - secure: "MgGKDY0805n/sq1kIUxaK8T5YG4jucI5JDPIl/UXVwqDqK8kCZMkPCUN2GPDl01cLdqrtCESVLLxY7Z3N7iayVW0SsxlbhZuI0+u6Ld+NOP5v6AheyNhDhowV2dCURItzszddEtKmCDGsR635l5LMb1SL4RFQNyUJtyyth3Z5j/pEV3rYN3ZwgWZByReNzNXypfOCYUmgeYqqR1lRO/I1/1VPTxIaTmn5AT5rI+PEY43c9+PLlPagtpM3WfYB9ATelfwo7QUrfd0eUliJhg2qi4hoZnT3c0Zc2FRRkDKP7/OUCDqL3w7ByCZnbvtPV4Hb6ogK0QqpQ2buOdl7m1sRWKJTvRAWmmIGKtPmbnDt8JIEov70sp0amhsS5PqVVTZu1Q7ZV6wVK9snNpjuDt1wkuwSBQBEokJTUZcs8qeHjomjPjkDJktzwhhWWUmhQf8A+SxGBOgvsr7D1oCjT1NE7VQ7j+wbuK4Kf8sfhlDp8USbEokrdMLQu9ZqbTx5TWbXZxx/wSyfyXJ5UXqz6lSyGMTGcVDhSO2vGS0YJphS+qM26SeILeBxodmfZQf+xZJhrqgo4L7P0yh98v+3bnCGAPPuTmH1+dgrNSdk3eVVjyVLF4ILjnlI+s/g5+F2824sxPsrf/2yam2YJ478vMXBLGYmATifWWli5o9dt9eyuM="
    - secure: "Mj7aK7zMhdrBM/nOXSSjkgLrU1M42Ya88Bp05g+vlawa4/rr4BWZWX/4Hs2VY/+t/HS3psDhqO+3WXhcKSk6yA8k+pfRjuuxmlvIkUbJlXcY8QuLNCz/Ycyq1FdrL9f38hvp1/OZvvwCxMkoIJ41jzTO5++4QMn6+hgQVxWJLFcMc45cNEZxwyTvAWNNZFGqdf7d01gySfjXr2ycow9DV6ZhhhbNV3XtjVcBJvLefYh0B2SucwfcYOy7mw+DtilREKtz3g1+KUVhm6PtFaRZG2qotUWXgcpQxn+iV8DF89G6SrqoKsabkP+gXq4AcyOalaWGPfpk1OeVYabbtzr3eIpMnH8sGVQHB+vpMHP/++K7vJMvZs5E8zKFdUwPQUHULPDqKqFi4qCW3hP7bSVH8pnAOd2VC06uTDcLyHmNVTizvNVyLQB1wk5/NCaKJQHnP3fMRJd4a+/sEBBVF7LyuOki/v0OuxWX0p4BHwHJ7/L7CdUOZDjAXrVOJn+mq5duaCuLDATOzw6VRxzBkNvlyhfL+cpXJgIXhP6KZ3ZRCzEOL8iurOyB/5I0hyuQ7ObUmobY/VL3obUho7fl49JO47vTD8lGgPU9BWooUnavOzXES5sdzopGepO96lT9vy7jad70sSLXikSIw50p7o15ZTImsPRlEr73Qg2RZKKp/wo="
branches:
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
before_install:
  # Expose DB to Docker container
  - sudo ./bin/ci/init-db.sh
before_script:
  # Extract project name and version from mix.exs
  - source ./bin/ci/rel/fetch-project-environment.sh
  # Load information about new version
  - source ./bin/ci/release/fetch-source-version.sh
  # Load information about changelog
  - source ./bin/ci/release/fetch-changelog.sh
script:
  # Check for versioning error
  - ./bin/ci/release/check-version-error.sh || travis_terminate 1
  # Increment version in mix.exs
  - ./bin/ci/release/put-source-version.sh || travis_terminate 1
  # Create release notes log for minor version
  # - ./bin/ci/release/put-release-notes.sh
  # Run all tests except pending ones
  - ./bin/mix_tests.sh || travis_terminate 1
  # Build Docker container
  - ./bin/ci/rel/build-container.sh || travis_terminate 1
  # Initialize DB for Docker container
  - (cd apps/event_manager_api && MIX_ENV=dev mix ecto.setup)
  # Run Docker container
  - sudo ./bin/ci/release/start-container.sh
  - sudo ./bin/ci/release/check-container.sh || travis_terminate
  # Submit Docker container to Docker Hub and create GitHub Release by pushing tag with changelog
  - ./bin/ci/rel/push-changes.sh || travis_terminate 1
  # - openssl aes-256-cbc -K $encrypted_c996ec964e08_key -iv $encrypted_c996ec964e08_iv -in eHealth-8110bd102a69.json.enc -out eHealth-8110bd102a69.json -d
  # - sudo ./bin/deploy.sh || travis_terminate 1
